"""
Text2SQL Streamlit Application

A Streamlit app that allows users to:
1. Upload Excel files
2. Ask questions in natural language
3. Get answers using SQL queries generated by LLM

This is different from RAG - it uses Text2SQL for structured data queries.
"""

import os
import tempfile
from pathlib import Path
import streamlit as st
import pandas as pd

from text2sql import Text2SQLPipeline

# Page setup
st.set_page_config(
    page_title="Text2SQL - Excel Query",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
<style>
.sql-query {
    background-color: #1e1e1e;
    color: #d4d4d4;
    padding: 1rem;
    border-radius: 0.5rem;
    font-family: 'Courier New', monospace;
    overflow-x: auto;
}
.result-table {
    margin-top: 1rem;
}
</style>
""", unsafe_allow_html=True)


def init_session_state():
    """Initialize session state variables."""
    if "pipeline" not in st.session_state:
        st.session_state.pipeline = Text2SQLPipeline()
    if "file_loaded" not in st.session_state:
        st.session_state.file_loaded = False
    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []
    if "df_preview" not in st.session_state:
        st.session_state.df_preview = None


def render_header():
    """Render the app header."""
    st.title("📊 Text2SQL - Excel Query System")
    st.markdown("""
    **Ask questions about your Excel data in natural language!**
    
    This app uses Text2SQL (not RAG) to query structured Excel data:
    - Upload an Excel file (.xlsx, .xls)
    - Ask questions like "What is the average age?" or "Who has the highest salary?"
    - Get instant answers with the generated SQL query
    """)
    st.divider()


def render_upload_section():
    """Render the file upload section."""
    st.subheader("📤 Upload Excel File")
    
    col1, col2 = st.columns([2, 1])
    
    with col1:
        uploaded_file = st.file_uploader(
            "Choose an Excel file",
            type=["xlsx", "xls"],
            help="Upload an Excel file to query"
        )
    
    with col2:
        table_name = st.text_input(
            "Table Name",
            value="excel_data",
            help="Name for the database table"
        )
    
    if uploaded_file:
        # Save to temp file
        with tempfile.NamedTemporaryFile(delete=False, suffix=Path(uploaded_file.name).suffix) as tmp:
            tmp.write(uploaded_file.getvalue())
            tmp_path = tmp.name
        
        try:
            # Load into database
            with st.spinner("Loading Excel file into database..."):
                success, message, row_count = st.session_state.pipeline.load_excel_to_db(
                    tmp_path, 
                    table_name
                )
            
            if success:
                st.success(f"✅ {message}")
                st.session_state.file_loaded = True
                
                # Preview the data
                df = pd.read_excel(tmp_path)
                st.session_state.df_preview = df
                
                with st.expander("📊 Data Preview (first 5 rows)"):
                    st.dataframe(df.head(), use_container_width=True)
                    st.info(f"Total rows: {len(df)}, Columns: {list(df.columns)}")
            else:
                st.error(f"❌ {message}")
                
        finally:
            os.unlink(tmp_path)
    
    return uploaded_file


def render_schema_section():
    """Render the database schema section."""
    if st.session_state.file_loaded:
        with st.expander("📋 Database Schema"):
            schema = st.session_state.pipeline.get_schema_info()
            st.code(schema, language="python")


def render_chat_section():
    """Render the Q&A chat section."""
    st.divider()
    st.subheader("💬 Ask Questions")
    
    if not st.session_state.file_loaded:
        st.info("👆 Please upload an Excel file first to start asking questions.")
        return
    
    # Display chat history
    for msg in st.session_state.chat_history:
        if msg["role"] == "user":
            st.markdown(f"**🧑 You:** {msg['content']}")
        else:
            st.markdown(f"**🤖 Assistant:** {msg['content']}")
            
            # Show SQL query
            if msg.get("sql_query"):
                with st.expander("🔍 View SQL Query"):
                    st.code(msg["sql_query"], language="sql")
            
            # Show results table
            if msg.get("results"):
                with st.expander("📊 View Raw Results"):
                    df = pd.DataFrame(msg["results"])
                    st.dataframe(df, use_container_width=True)
            
            st.divider()
    
    # Question input
    col1, col2 = st.columns([5, 1])
    
    with col1:
        question = st.text_input(
            "Ask a question about your data:",
            placeholder="e.g., What is the average salary by department?",
            label_visibility="collapsed"
        )
    
    with col2:
        ask_button = st.button("Ask", type="primary", use_container_width=True)
    
    if ask_button and question.strip():
        # Add user message to history
        st.session_state.chat_history.append({
            "role": "user",
            "content": question
        })
        
        # Get answer
        with st.spinner("Generating SQL and executing query..."):
            result = st.session_state.pipeline.answer(question)
        
        # Add assistant message to history
        st.session_state.chat_history.append({
            "role": "assistant",
            "content": result["answer"],
            "sql_query": result.get("sql_query", ""),
            "results": result.get("results", [])
        })
        
        # Rerun to show new message
        st.rerun()


def render_sidebar():
    """Render the sidebar."""
    with st.sidebar:
        st.markdown("# 📊 Text2SQL")
        st.markdown("---")
        
        st.markdown("### ℹ️ How it works")
        st.markdown("""
        1. **Upload** an Excel file
        2. Data is stored in **SQLite** database
        3. Ask questions in **natural language**
        4. LLM generates **SQL queries**
        5. Get **instant answers**
        """)
        
        st.markdown("---")
        
        st.markdown("### 📝 Example Questions")
        st.markdown("""
        - "What is the total sales?"
        - "Who has the highest salary?"
        - "Show top 10 customers"
        - "Average age by department"
        - "Count of employees by country"
        """)
        
        st.markdown("---")
        
        # Clear history button
        if st.button("🗑️ Clear Chat History", use_container_width=True):
            st.session_state.chat_history = []
            st.rerun()
        
        # Reset database button
        if st.button("🔄 Reset Database", use_container_width=True):
            st.session_state.pipeline.close()
            st.session_state.pipeline = Text2SQLPipeline()
            st.session_state.file_loaded = False
            st.session_state.df_preview = None
            st.session_state.chat_history = []
            st.rerun()


def main():
    """Main application entry point."""
    init_session_state()
    render_header()
    render_sidebar()
    render_upload_section()
    render_schema_section()
    render_chat_section()


if __name__ == "__main__":
    main()